# Generated by Django 5.1.4 on 2024-12-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('tuition_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('program_level', models.CharField(choices=[('D', 'Diploma'), ('B', 'Bachelor'), ('M', 'Master'), ('P', 'PhD')], max_length=1)),
                ('course_title', models.CharField(max_length=200)),
            ],
        ),
    ]
