# Generated by Django 5.1.4 on 2024-12-07 00:34

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    University = apps.get_model("university", "University")
    seen_names = set()
    for university in University.objects.all():
        if university.university_name in seen_names:
            university.delete()
        else:
            seen_names.add(university.university_name)


class Migration(migrations.Migration):

    dependencies = [
        ("university", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
    ]
