# Generated by Django 5.1.4 on 2024-12-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_cleanup_university_name_duplicates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
